server:
  port: 8080
  servlet:
    context-path: /demo
spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/demo_service}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "Ko5NqGtjMiv5b/aTUrmtDp9BOXoGTl1box2QoIYVdjBnJjH/9hGYkKGlKJurPwwL"
  valid-duration: 3600 #in second
  refreshable-duration: 36000 #in second